services:
  - type: web
    name: edutrak
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      
      python manage.py migrate
    startCommand: gunicorn CoachHub.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: CoachHub.settings
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: edutrak-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.9

databases:
  - name: edutrak-db
    plan: free
    region: oregon
